// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yact.Infrastructure.Persistence.Data;

#nullable disable

namespace Yact.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251217100303_AddCyclistFitnessWithPowerZones")]
    partial class AddCyclistFitnessWithPowerZones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Activity.ActivityInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CyclistId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("float");

                    b.Property<double>("ElevationMeters")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId");

                    b.ToTable("ActivityInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 12, 17, 11, 3, 2, 490, DateTimeKind.Local).AddTicks(9097),
                            CyclistId = 1,
                            Description = "This is a dummy activity",
                            DistanceMeters = 10000.0,
                            ElevationMeters = 100.0,
                            EndDate = new DateTime(2025, 12, 17, 11, 3, 2, 490, DateTimeKind.Local).AddTicks(9094),
                            Name = "Dummy Activity",
                            Path = "dummy_activity.fit",
                            StartDate = new DateTime(2025, 12, 17, 10, 33, 2, 490, DateTimeKind.Local).AddTicks(9089),
                            Type = "Cycling"
                        });
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Analytics.Interval", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityInfoId")
                        .HasColumnType("int");

                    b.Property<float>("AverageCadence")
                        .HasColumnType("real");

                    b.Property<float>("AverageHeartRate")
                        .HasColumnType("real");

                    b.Property<float>("AveragePower")
                        .HasColumnType("real");

                    b.Property<float>("Distance")
                        .HasColumnType("real");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("MaxCadence")
                        .HasColumnType("real");

                    b.Property<float>("MaxHeartRate")
                        .HasColumnType("real");

                    b.Property<float>("MaxPower")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ActivityInfoId");

                    b.ToTable("Intervals");
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Climb.ActivityClimb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<int>("ClimbId")
                        .HasColumnType("int");

                    b.Property<double>("StartPointMeters")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ClimbId");

                    b.ToTable("ActivityClimbs");
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Climb.ClimbInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AltitudeEnd")
                        .HasColumnType("float");

                    b.Property<double>("AltitudeInit")
                        .HasColumnType("float");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("float");

                    b.Property<double>("Elevation")
                        .HasColumnType("float");

                    b.Property<double>("LatitudeEnd")
                        .HasColumnType("float");

                    b.Property<double>("LatitudeInit")
                        .HasColumnType("float");

                    b.Property<double>("LongitudeEnd")
                        .HasColumnType("float");

                    b.Property<double>("LongitudeInit")
                        .HasColumnType("float");

                    b.Property<double>("MaxSlope")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Slope")
                        .HasColumnType("float");

                    b.Property<bool>("Validated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Climbs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltitudeEnd = 0.0,
                            AltitudeInit = 0.0,
                            DistanceMeters = 0.0,
                            Elevation = 0.0,
                            LatitudeEnd = 0.0,
                            LatitudeInit = 0.0,
                            LongitudeEnd = 0.0,
                            LongitudeInit = 0.0,
                            MaxSlope = 0.0,
                            Name = "Unknown",
                            Slope = 0.0,
                            Validated = true
                        });
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Cyclist.CyclistFitness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CyclistId")
                        .HasColumnType("int");

                    b.Property<int>("Ftp")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("HrZonesRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerCurveJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerZonesRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Vo2Max")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId");

                    b.ToTable("CyclistFitnesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CyclistId = 1,
                            Ftp = 250,
                            Height = 180,
                            PowerZonesRaw = "[\r\n                {\"lowLimit\": 0, \"highLimit\":150},\r\n                {\"lowLimit\": 151, \"highLimit\": 200},\r\n                {\"lowLimit\": 201, \"highLimit\": 250},\r\n                {\"lowLimit\": 251, \"highLimit\": 300},\r\n                {\"lowLimit\": 301, \"highLimit\": 350},\r\n                {\"lowLimit\": 351, \"highLimit\": 400},\r\n                {\"lowLimit\": 401, \"highLimit\": 500}\r\n            ]",
                            UpdateDate = new DateTime(2025, 12, 17, 11, 3, 2, 490, DateTimeKind.Local).AddTicks(8979),
                            Vo2Max = 50f,
                            Weight = 70f
                        });
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Cyclist.CyclistInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CyclistInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2025, 12, 17, 11, 3, 2, 490, DateTimeKind.Local).AddTicks(8782),
                            LastName = "Cyclist",
                            Name = "Dummy"
                        });
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Activity.ActivityInfo", b =>
                {
                    b.HasOne("Yact.Infrastructure.Persistence.Models.Cyclist.CyclistInfo", "Cyclist")
                        .WithMany("Activities")
                        .HasForeignKey("CyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cyclist");
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Analytics.Interval", b =>
                {
                    b.HasOne("Yact.Infrastructure.Persistence.Models.Activity.ActivityInfo", "ActivityInfo")
                        .WithMany("Intervals")
                        .HasForeignKey("ActivityInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityInfo");
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Climb.ActivityClimb", b =>
                {
                    b.HasOne("Yact.Infrastructure.Persistence.Models.Activity.ActivityInfo", "Activity")
                        .WithMany("Climbs")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yact.Infrastructure.Persistence.Models.Climb.ClimbInfo", "Climb")
                        .WithMany("Efforts")
                        .HasForeignKey("ClimbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Climb");
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Cyclist.CyclistFitness", b =>
                {
                    b.HasOne("Yact.Infrastructure.Persistence.Models.Cyclist.CyclistInfo", "Cyclist")
                        .WithMany("Fitnesss")
                        .HasForeignKey("CyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cyclist");
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Activity.ActivityInfo", b =>
                {
                    b.Navigation("Climbs");

                    b.Navigation("Intervals");
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Climb.ClimbInfo", b =>
                {
                    b.Navigation("Efforts");
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Cyclist.CyclistInfo", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Fitnesss");
                });
#pragma warning restore 612, 618
        }
    }
}
