// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yact.Infrastructure.Persistence.Data;

#nullable disable

namespace Yact.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207121822_FirstDbUpload")]
    partial class FirstDbUpload
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Activity.ActivityInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CyclistId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("float");

                    b.Property<double>("ElevationMeters")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 12, 7, 13, 18, 22, 92, DateTimeKind.Local).AddTicks(7982),
                            CyclistId = 1,
                            Description = "This is a dummy activity",
                            DistanceMeters = 10000.0,
                            ElevationMeters = 100.0,
                            EndDate = new DateTime(2025, 12, 7, 13, 18, 22, 92, DateTimeKind.Local).AddTicks(7980),
                            Name = "Dummy Activity",
                            Path = "dummy_activity.fit",
                            StartDate = new DateTime(2025, 12, 7, 12, 48, 22, 92, DateTimeKind.Local).AddTicks(7975),
                            Type = "Cycling"
                        });
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Cyclist.CyclistFitness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CyclistId")
                        .HasColumnType("int");

                    b.Property<int>("Ftp")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<string>("HrZonesRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerCurveJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerZonesRaw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Vo2Max")
                        .HasColumnType("real");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("CyclistFitnesses");
                });

            modelBuilder.Entity("Yact.Infrastructure.Persistence.Models.Cyclist.CyclistInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CyclistInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2025, 12, 7, 13, 18, 22, 92, DateTimeKind.Local).AddTicks(7775),
                            LastName = "Cyclist",
                            Name = "Dummy"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
