// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yact.Infrastructure.Data;

#nullable disable

namespace Yact.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203151823_AddDummyActivityToDb")]
    partial class AddDummyActivityToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yact.Domain.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("float");

                    b.Property<double>("ElevationMeters")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2025, 12, 3, 16, 18, 22, 825, DateTimeKind.Local).AddTicks(3230),
                            Description = "This is a dummy activity",
                            DistanceMeters = 10000.0,
                            ElevationMeters = 100.0,
                            EndDate = new DateTime(2025, 12, 3, 16, 18, 22, 825, DateTimeKind.Local).AddTicks(3228),
                            IsIndoor = false,
                            Name = "Dummy Activity",
                            Path = "dummy_activity.fit",
                            StartDate = new DateTime(2025, 12, 3, 15, 48, 22, 825, DateTimeKind.Local).AddTicks(3176)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
