// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yact.Infrastructure.Persistence.Data;

#nullable disable

namespace Yact.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260115113659_ActivityClimbToActivityAggregate")]
    partial class ActivityClimbToActivityAggregate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yact.Domain.Entities.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CyclistId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId");

                    b.ToTable("Activities", (string)null);
                });

            modelBuilder.Entity("Yact.Domain.Entities.ActivityClimb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClimbId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("StartPointMeters")
                        .HasColumnType("float")
                        .HasColumnName("StartPointMeters");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ClimbId");

                    b.ToTable("ActivityClimbs", (string)null);
                });

            modelBuilder.Entity("Yact.Domain.Entities.Climb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.HasKey("Id");

                    b.ToTable("Climbs", (string)null);
                });

            modelBuilder.Entity("Yact.Domain.Entities.Cyclist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Cyclists", (string)null);
                });

            modelBuilder.Entity("Yact.Domain.Entities.CyclistFitness", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("CyclistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ftp")
                        .HasColumnType("int")
                        .HasColumnName("FTP");

                    b.Property<string>("HrZones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerCurve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerZones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<float>("Vo2Max")
                        .HasColumnType("real")
                        .HasColumnName("VO2Max");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId", "UpdateDate")
                        .HasDatabaseName("IX_CyclistFitnesses_CyclistId_UpdateDate");

                    b.ToTable("CyclistFitnesses", (string)null);
                });

            modelBuilder.Entity("Yact.Domain.Entities.Activity", b =>
                {
                    b.HasOne("Yact.Domain.Entities.Cyclist", null)
                        .WithMany()
                        .HasForeignKey("CyclistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Yact.Domain.ValueObjects.Activity.ActivitySummary", "Summary", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreateDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("CreationDate");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.Property<double>("DistanceMeters")
                                .HasColumnType("float")
                                .HasColumnName("DistanceMeters");

                            b1.Property<double>("ElevationMeters")
                                .HasColumnType("float")
                                .HasColumnName("ElevationMeters");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("EndDate");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Name");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("StartDate");

                            b1.Property<string>("Type")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Type");

                            b1.Property<DateTime?>("UpdateDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("UpdateDate");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.OwnsOne("Yact.Domain.ValueObjects.Activity.FilePath", "Path", b1 =>
                        {
                            b1.Property<Guid>("ActivityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Path");

                            b1.HasKey("ActivityId");

                            b1.ToTable("Activities");

                            b1.WithOwner()
                                .HasForeignKey("ActivityId");
                        });

                    b.Navigation("Path")
                        .IsRequired();

                    b.Navigation("Summary")
                        .IsRequired();
                });

            modelBuilder.Entity("Yact.Domain.Entities.ActivityClimb", b =>
                {
                    b.HasOne("Yact.Domain.Entities.Activity", null)
                        .WithMany("Climbs")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yact.Domain.Entities.Climb", null)
                        .WithMany()
                        .HasForeignKey("ClimbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Yact.Domain.Entities.Climb", b =>
                {
                    b.OwnsOne("Yact.Domain.ValueObjects.Climb.ClimbDetails", "Data", b1 =>
                        {
                            b1.Property<Guid>("ClimbId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("StartPointMeters")
                                .HasColumnType("float")
                                .HasColumnName("StartPointMeters");

                            b1.HasKey("ClimbId");

                            b1.ToTable("Climbs");

                            b1.WithOwner()
                                .HasForeignKey("ClimbId");

                            b1.OwnsOne("Yact.Domain.ValueObjects.Climb.ClimbCoordinates", "Coordinates", b2 =>
                                {
                                    b2.Property<Guid>("ClimbDetailsClimbId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("AltitudeEnd")
                                        .HasColumnType("float")
                                        .HasColumnName("AltitudeEnd");

                                    b2.Property<double>("AltitudeInit")
                                        .HasColumnType("float")
                                        .HasColumnName("AltitudeInit");

                                    b2.Property<double>("LatitudeEnd")
                                        .HasColumnType("float")
                                        .HasColumnName("LatitudeEnd");

                                    b2.Property<double>("LatitudeInit")
                                        .HasColumnType("float")
                                        .HasColumnName("LatitudeInit");

                                    b2.Property<double>("LongitudeEnd")
                                        .HasColumnType("float")
                                        .HasColumnName("LongitudeEnd");

                                    b2.Property<double>("LongitudeInit")
                                        .HasColumnType("float")
                                        .HasColumnName("LongitudeInit");

                                    b2.HasKey("ClimbDetailsClimbId");

                                    b2.ToTable("Climbs");

                                    b2.WithOwner()
                                        .HasForeignKey("ClimbDetailsClimbId");
                                });

                            b1.OwnsOne("Yact.Domain.ValueObjects.Climb.ClimbMetrics", "Metrics", b2 =>
                                {
                                    b2.Property<Guid>("ClimbDetailsClimbId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<double>("DistanceMeters")
                                        .HasColumnType("float")
                                        .HasColumnName("DistanceMeters");

                                    b2.Property<double>("MaxSlope")
                                        .HasColumnType("float")
                                        .HasColumnName("MaxSlope");

                                    b2.Property<double>("NetElevationMeters")
                                        .HasColumnType("float")
                                        .HasColumnName("NetElevationMeters");

                                    b2.Property<double>("Slope")
                                        .HasColumnType("float")
                                        .HasColumnName("Slope");

                                    b2.Property<double>("TotalElevationMeters")
                                        .HasColumnType("float")
                                        .HasColumnName("TotalElevationMeters");

                                    b2.HasKey("ClimbDetailsClimbId");

                                    b2.ToTable("Climbs");

                                    b2.WithOwner()
                                        .HasForeignKey("ClimbDetailsClimbId");
                                });

                            b1.Navigation("Coordinates")
                                .IsRequired();

                            b1.Navigation("Metrics")
                                .IsRequired();
                        });

                    b.OwnsOne("Yact.Domain.ValueObjects.Climb.ClimbSummary", "Summary", b1 =>
                        {
                            b1.Property<Guid>("ClimbId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Name");

                            b1.HasKey("ClimbId");

                            b1.ToTable("Climbs");

                            b1.WithOwner()
                                .HasForeignKey("ClimbId");
                        });

                    b.Navigation("Data")
                        .IsRequired();

                    b.Navigation("Summary")
                        .IsRequired();
                });

            modelBuilder.Entity("Yact.Domain.Entities.CyclistFitness", b =>
                {
                    b.HasOne("Yact.Domain.Entities.Cyclist", null)
                        .WithMany("FitnessHistory")
                        .HasForeignKey("CyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Yact.Domain.ValueObjects.Cyclist.Size", "Size", b1 =>
                        {
                            b1.Property<Guid>("CyclistFitnessId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("HeightCm")
                                .HasColumnType("int")
                                .HasColumnName("Height");

                            b1.Property<float>("WeightKg")
                                .HasColumnType("real")
                                .HasColumnName("Weight");

                            b1.HasKey("CyclistFitnessId");

                            b1.ToTable("CyclistFitnesses");

                            b1.WithOwner()
                                .HasForeignKey("CyclistFitnessId");
                        });

                    b.Navigation("Size")
                        .IsRequired();
                });

            modelBuilder.Entity("Yact.Domain.Entities.Activity", b =>
                {
                    b.Navigation("Climbs");
                });

            modelBuilder.Entity("Yact.Domain.Entities.Cyclist", b =>
                {
                    b.Navigation("FitnessHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
