// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yact.Infrastructure.Persistence.Data;

#nullable disable

namespace Yact.Infrastructure.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    [Migration("20260109121733_correctTables")]
    partial class correctTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yact.Domain.Entities.Cyclist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Cyclists", (string)null);
                });

            modelBuilder.Entity("Yact.Domain.Entities.CyclistFitness", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("CyclistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ftp")
                        .HasColumnType("int")
                        .HasColumnName("FTP");

                    b.Property<string>("HrZones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerCurve")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerZones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdateDate");

                    b.Property<float>("Vo2Max")
                        .HasColumnType("real")
                        .HasColumnName("VO2Max");

                    b.HasKey("Id");

                    b.HasIndex("CyclistId", "UpdateDate")
                        .HasDatabaseName("IX_CyclistFitnesses_CyclistId_UpdateDate");

                    b.ToTable("CyclistFitnesses", (string)null);
                });

            modelBuilder.Entity("Yact.Domain.Entities.CyclistFitness", b =>
                {
                    b.HasOne("Yact.Domain.Entities.Cyclist", null)
                        .WithMany("_fitnessHistory")
                        .HasForeignKey("CyclistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Yact.Domain.ValueObjects.Cyclist.Size", "Size", b1 =>
                        {
                            b1.Property<Guid>("CyclistFitnessId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("HeightCm")
                                .HasColumnType("int")
                                .HasColumnName("Height");

                            b1.Property<float>("WeightKg")
                                .HasColumnType("real")
                                .HasColumnName("Weight");

                            b1.HasKey("CyclistFitnessId");

                            b1.ToTable("CyclistFitnesses");

                            b1.WithOwner()
                                .HasForeignKey("CyclistFitnessId");
                        });

                    b.Navigation("Size")
                        .IsRequired();
                });

            modelBuilder.Entity("Yact.Domain.Entities.Cyclist", b =>
                {
                    b.Navigation("_fitnessHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
