// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YactAPI.Data;

#nullable disable

namespace YactAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202150233_AddFileDetailsToActivity")]
    partial class AddFileDetailsToActivity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YactAPI.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dummy Activity",
                            Path = "dummy_activity.fit"
                        });
                });

            modelBuilder.Entity("YactAPI.Models.Climb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AltitudeEnd")
                        .HasColumnType("float");

                    b.Property<double>("AltitudeInit")
                        .HasColumnType("float");

                    b.Property<double>("AverageSlope")
                        .HasColumnType("float");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<double>("EndRouteDistance")
                        .HasColumnType("float");

                    b.Property<double>("HeightDiff")
                        .HasColumnType("float");

                    b.Property<double>("InitRouteDistance")
                        .HasColumnType("float");

                    b.Property<double>("LatitudeEnd")
                        .HasColumnType("float");

                    b.Property<double>("LatitudeInit")
                        .HasColumnType("float");

                    b.Property<double>("LongitudeEnd")
                        .HasColumnType("float");

                    b.Property<double>("LongitudeInit")
                        .HasColumnType("float");

                    b.Property<double>("MaxSlope")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Climbs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AltitudeEnd = 0.0,
                            AltitudeInit = 0.0,
                            AverageSlope = 0.0,
                            Distance = 0.0,
                            EndRouteDistance = 0.0,
                            HeightDiff = 0.0,
                            InitRouteDistance = 0.0,
                            LatitudeEnd = 0.0,
                            LatitudeInit = 0.0,
                            LongitudeEnd = 0.0,
                            LongitudeInit = 0.0,
                            MaxSlope = 0.0,
                            Name = "Dummy Climb",
                            Path = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
